"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, Eye, MessageSquareText, MoreHorizontal, Plus, Sparkles, Users } from "lucide-react";
import { games } from "@/lib/data";

export default function CreatorPage() {
  const own = games.slice(0, 2);
  return (
    <main className="dashboard-page creator-dashboard"><section className="shell dashboard-header"><div><span className="kicker">CREATOR STUDIO</span><h1>作品とプレイヤーの今。</h1><p>おかえりなさい、Studio Pebbleさん。</p></div><Link className="button primary" href="/creator/games/new"><Plus size={18} /> 新しい作品を登録</Link></section><section className="shell stat-grid creator-stats"><article><Eye /><span>今月のプレイ</span><strong>2,748</strong><p className="up">↗ 18.4%</p></article><article><Users /><span>ユニークプレイヤー</span><strong>1,806</strong><p className="up">↗ 12.1%</p></article><article><MessageSquareText /><span>届いた新しい気づき</span><strong>38</strong><p>未読 12件</p></article><article className="point-stat"><Sparkles /><span>届いた応援</span><strong>12,480<small> pt</small></strong><p>支援分配の参考指標</p></article></section><section className="shell creator-main"><div className="dashboard-panel"><div className="panel-heading"><div><span className="kicker">YOUR GAMES</span><h2>公開作品</h2></div><button>すべて表示</button></div><div className="creator-games">{own.map((game, i) => <article key={game.slug}><div className="creator-game-cover"><Image src={game.image} fill sizes="180px" alt="" /></div><div className="creator-game-info"><div><span className={`status-dot ${i ? "review" : ""}`}>{i ? "審査中" : "公開中"}</span><small>{game.stage}</small></div><h3>{game.title}</h3><div className="creator-metrics"><span><Eye /> {game.plays}</span><span><MessageSquareText /> {i ? 14 : 38}</span><span><Sparkles /> {i ? 320 : 1840}</span></div><div className="progress-line"><i style={{ width: `${game.progress}%` }} /></div></div><button className="more"><MoreHorizontal /></button></article>)}</div></div><aside className="dashboard-panel pulse-panel"><div className="panel-heading"><div><span className="kicker">PLAYER NOTICES</span><h2>最近届いた気づき</h2></div></div><div className="sentiment"><div><strong>4.6</strong><span>平均評価</span></div><div className="sentiment-bar"><i style={{ width: "82%" }} /></div><b>とても好評</b></div><div className="comment"><span>改善アイデア</span><p>「岩を割ったときの手応えが気持ちいい。音がもっと種類あると嬉しい！」</p><small>COREBREAK ・ 2時間前</small></div><div className="comment"><span>分かりにくい</span><p>「拠点を作った後の目標が少し分かりにくかったです。」</p><small>PIXEL HEARTH ・ 5時間前</small></div><Link href="#">すべての気づきを見る <ArrowRight /></Link></aside></section><section className="shell insight-banner"><BarChart3 /><div><span className="kicker">WEEKLY INSIGHT</span><h2>チュートリアル完了率が 12% 改善しました</h2><p>v0.4公開後、最初のクエストまで到達するプレイヤーが増えています。</p></div><button className="button ghost-light">分析を見る</button></section></main>
  );
}
