"use client";

import Link from "next/link";
import { ArrowLeft, Check, ImagePlus, Link2, Save } from "lucide-react";
import { useState } from "react";

export default function NewGamePage() {
  const [step, setStep] = useState(1);
  const [saved, setSaved] = useState(false);
  return (
    <main className="editor-page"><div className="shell editor-top"><Link href="/creator"><ArrowLeft /> Creator Studio</Link><div><button className="button ghost" onClick={() => setSaved(true)}><Save size={17} /> 下書き保存</button><button className="button primary" onClick={() => setStep(Math.min(3, step + 1))}>{step === 3 ? "審査に提出" : "次へ"}</button></div></div><section className="shell editor-layout"><aside className="editor-steps"><span className="kicker">NEW PROJECT</span><h1>作品を登録</h1>{["基本情報", "プレイビルド", "公開設定"].map((label, i) => <button className={step === i + 1 ? "active" : step > i + 1 ? "done" : ""} onClick={() => setStep(i + 1)} key={label}><span>{step > i + 1 ? <Check /> : i + 1}</span><div><b>{label}</b><small>{["作品の顔をつくる", "遊べるURLを接続", "内容を確認して提出"][i]}</small></div></button>)}</aside><div className="editor-form">{saved && <div className="save-notice"><Check /> 下書きを保存しました</div>}{step === 1 && <><span className="kicker">STEP 01 / 03</span><h2>どんなゲームですか？</h2><p>あとからいつでも変更できます。まずはプレイヤーに伝わる言葉を置いてみましょう。</p><label>ゲームタイトル <em>必須</em><input defaultValue="STARLING ARCHIVE" /></label><label>ひとこと紹介 <em>必須</em><input defaultValue="失われた星の記憶を集める、静かな探索アドベンチャー。" /></label><div className="field-row"><label>ジャンル<select defaultValue="アドベンチャー"><option>アドベンチャー</option><option>パズル</option><option>アクション</option></select></label><label>開発ステージ<select defaultValue="プロトタイプ"><option>プロトタイプ</option><option>アルファ</option><option>ベータ</option></select></label></div><label>作品について<textarea defaultValue="宇宙を旅しながら、小さな物語の断片を集めていくゲームです。現在は最初の惑星まで遊べます。" /></label><label>カバー画像<div className="drop-zone"><ImagePlus /><b>画像をドロップ、または選択</b><span>PNG / JPG・16:9推奨・最大10MB</span></div></label></>}{step === 2 && <><span className="kicker">STEP 02 / 03</span><h2>プレイできるビルドをつなぐ</h2><p>現在のモックでは、許可済みドメインのデモURLを登録するStage Aを想定しています。</p><label>デモURL <em>必須</em><div className="input-icon"><Link2 /><input defaultValue="https://demo.example.com/starling" /></div></label><div className="info-box"><b>公開前の安全チェック</b><ul><li>HTTPSで配信されている</li><li>ブラウザ内で完結している</li><li>外部決済や不審なダウンロードがない</li></ul></div><label>今回のバージョン<input defaultValue="ALPHA 0.1" /></label><label>プレイヤーに聞きたいこと<textarea defaultValue="移動操作はわかりやすかったですか？ 星の記憶をもっと集めたいと感じましたか？" /></label></>}{step === 3 && <><span className="kicker">STEP 03 / 03</span><h2>公開内容を確認</h2><p>審査提出後、運営がデモURLと掲載内容を確認します。</p><div className="review-card"><div><span>タイトル</span><b>STARLING ARCHIVE</b></div><div><span>ステージ</span><b>プロトタイプ</b></div><div><span>デモURL</span><b>接続済み</b></div><div><span>公開範囲</span><b>全プレイヤー</b></div></div><label className="check-label"><input type="checkbox" defaultChecked /> 投稿ガイドラインと安全ポリシーに同意します</label><button className="button primary wide" onClick={() => setSaved(true)}>運営審査に提出する</button></>}</div></section></main>
  );
}
